SET SERVEROUTPUT ON SIZE 500000
SET TIMING ON
SET ECHO ON
SET DEFINE OFF

SPOOL ./LOGS/PRISM_CONFIG_DETAILS.LOG

----------Audit insert------------

DELETE FROM PRISM_CONFIG_DETAILS WHERE RELEASE_ID = 'JNJ_ES_DR_13AUG2022_AHQC-6265';

INSERT INTO PRISM_CONFIG_DETAILS
(SEQ_EXECUTION , RELEASE_ID , RELEASE_DELIVERED_DATE , RELEASE_EXECUTION_DATE, TS_VERSION, REMARKS) VALUES
(Seq_Execution.NEXTVAL,'JNJ_ES_DR_13AUG2022_AHQC-6265',to_date('08-AUG-2022','DD-MON-YYYY'),SYSDATE,(SELECT ARIS_DBS_VERSION FROM aris_dbs_info),'DR Release JNJ_ES_DR_13AUG2022_AHQC-6265');

SELECT sys_context('userenv','instance_name') AS SID FROM dual;

COMMIT;
	
SET TIMING OFF;
SET DEFINE ON;
SPOOL OFF;

EXIT;